stages:
  - build

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t registry.gitlab.com/your-namespace/your-project-name/your-image-name:latest .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push registry.gitlab.com/your-namespace/your-project-name/your-image-name:latest
  only:
    - master
